#!/bin/bash
# Interactive Database Explorer

echo "🗃️  Pokemon Card Database Explorer"
echo "=================================="
echo ""
echo "Database: cards_backup_20251002_182725.db"
echo ""
echo "Quick Commands:"
echo ""
echo "1. View all tables:"
echo "   sqlite3 database/cards_backup_20251002_182725.db '.tables'"
echo ""
echo "2. View schema for cards table:"
echo "   sqlite3 database/cards_backup_20251002_182725.db '.schema cards'"
echo ""
echo "3. Count cards by set:"
echo "   sqlite3 database/cards_backup_20251002_182725.db \"SELECT s.name, COUNT(*) FROM sets s JOIN cards c ON s.id = c.set_id GROUP BY s.name LIMIT 10;\""
echo ""
echo "4. View expensive cards:"
echo "   sqlite3 database/cards_backup_20251002_182725.db \"SELECT name, current_value FROM cards WHERE current_value > 100 ORDER BY current_value DESC LIMIT 10;\""
echo ""
echo "5. Check missing pricing:"
echo "   sqlite3 database/cards_backup_20251002_182725.db \"SELECT COUNT(*) FROM cards WHERE current_value IS NULL OR current_value = 0;\""
echo ""
echo "6. Interactive SQL shell:"
echo "   sqlite3 database/cards_backup_20251002_182725.db"
echo ""
echo "📄 Full analysis document: DATABASE_STRUCTURE_ANALYSIS.md"
echo ""
